<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>NBenchmark.Extensions.NUnit.Tests</RootNamespace>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit3TestAdapter"/>
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NBenchmark.Extensions.NUnit\NBenchmark.Extensions.NUnit.csproj"/>
    <ProjectReference Include="..\..\src\NBenchmark\NBenchmark.csproj"/>
  </ItemGroup>

</Project>