<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NBenchmark\NBenchmark.csproj"/>
    <ProjectReference Include="..\..\src\NBenchmark.Reporters.Console\NBenchmark.Reporters.Console.csproj"/>
    <ProjectReference Include="..\..\src\NBenchmark.Extensions.DependencyInjection\NBenchmark.Extensions.DependencyInjection.csproj"/>
  </ItemGroup>

</Project>
