<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <RootNamespace>NBenchmark</RootNamespace>
    <PackageId>NBenchmark</PackageId>
    <Description>NBenchmark is the easiest way to measure the speed of your .NET code. With zero setup and a focus on simplicity, you can go from installation to your first accurate benchmark in seconds-perfect for quick checks and full performance suites alike.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>benchmark;performance;measurement;microbenchmark</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="NBenchmark.Tests"/>
    <InternalsVisibleTo Include="NBenchmark.DependencyInjection"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath=""/>
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="all"/>
  </ItemGroup>

</Project>
