<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\NBenchmark\NBenchmark.csproj" />
    <ProjectReference Include="..\..\src\NBenchmark.Console\NBenchmark.Console.csproj" />
  </ItemGroup>

</Project>